# Generated by Django 4.2.6 on 2024-01-19 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='događaj',
            name='volonteri',
            field=models.ManyToManyField(related_name='dogadaji', to='main.volonter'),
        ),
        migrations.AddField(
            model_name='projekt',
            name='volonteri',
            field=models.ManyToManyField(related_name='projekti', to='main.volonter'),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='organizator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizirani_projekti', to='main.volonter'),
        ),
    ]
